[package]
name = "near-event-streams"
version = "0.1.0"
authors = ["Sigil Network <contact@sigilnet.com>"]
edition = "2021"

[dependencies]
near-indexer = { git = "https://github.com/near/nearcore.git", rev = "d44ae4d6369abc8fe523492ff0911367a6e931af" }
actix = "0.13.0"
enum-map = "=2.1.0"
openssl-probe = "0.1.5"
tokio = { version = "1.1", features = ["sync", "time"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.81"
anyhow = "1.0"

[dev-dependencies]
cargo-husky = { version = "1.5.0", default-features = false, features = ["user-hooks"] }
