[target.x86_64-unknown-linux-gnu]
linker = "x86_64-unknown-linux-gnu-gcc"

[alias]
build-linux = "build --release --target x86_64-unknown-linux-gnu"
unit-test = "test"
integration-test = "test --test *"
