name: CI

on:
  push:
    branches:
      - 'build-image'

jobs:
  build_and_push_to_registry:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: $GITHUB_REPOSITORY:$GITHUB_REF_NAME
          cache-from: type=registry,ref=$GITHUB_REPOSITORY:buildcache
          cache-to: type=registry,ref=$GITHUB_REPOSITORY:buildcache,mode=max
